ad

diff --git a/.github/workflows/tagging.yml b/.github/workflows/tagging.yml
--- a/.github/workflows/tagging.yml
+++ b/.github/workflows/tagging.yml
@@ -77,12 +77,42 @@ jobs:
           git tag $NEW_TAG
           git push origin $NEW_TAG
 
+  check_module_exists:
+    name: Check Module Exists
+    runs-on: ubuntu-latest
+    needs: add_new_tag
+    steps:
+      - name: Check if module exists
+        id: check_module
+        env:
+          TF_API_TEAM_TOKEN: ${{ secrets.TF_API_TEAM_TOKEN }}
+          ORGANIZATION_NAME: veloso
+          MODULE_NAME: $(basename ${{ github.repository }})  # Extracts repo name as module name
+          PROVIDER_NAME: aws  # Adjust provider name if needed
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://app.terraform.io/api/v2/organizations/${{ env.ORGANIZATION_NAME }}/registry-modules/private/${{ env.ORGANIZATION_NAME }}/${{ env.MODULE_NAME }}/${{ env.PROVIDER_NAME }}" \
+            -H "Authorization: Bearer $TF_API_TEAM_TOKEN" \
+            -H "Accept: application/json")
+          
+          if [[ "$response" -eq 200 ]]; then
+            echo "Module $MODULE_NAME already exists."
+            echo "module_exists=true" >> $GITHUB_ENV
+          elif [[ "$response" -eq 404 ]]; then
+            echo "Module $MODULE_NAME does not exist, publishing now."
+            echo "module_exists=false" >> $GITHUB_ENV
+          else
+            echo "Error checking module status. Response code: $response"
+            exit 1
+          fi
+
+
   publish_hcp_module:
     name: Publish Terraform Module
     runs-on: ubuntu-latest
-    needs: add_new_tag
+    needs: check_module_exists
     steps:      
       - name: Conditional POST API Request to Publish Module
+        if: env.module_exists == 'false'
         env:
           TF_API_TEAM_TOKEN: ${{ secrets.TF_API_TEAM_TOKEN }}
           OAUTH_TOKEN_ID: ${{ secrets.OAUTH_TOKEN_ID }}
