add

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -64,8 +64,9 @@ jobs:
           OAUTH_TOKEN_ID: ${{ secrets.OAUTH_TOKEN_ID }}
           ORGANIZATION_NAME: veloso
           WORKSPACE_NAME: ${{ needs.get_repo_name.outputs.sanitized_repo_name }}
+        id: create_workspace
         run: |
-          curl -X POST "https://app.terraform.io/api/v2/organizations/${{ env.ORGANIZATION_NAME }}/workspaces" \
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://app.terraform.io/api/v2/organizations/${{ env.ORGANIZATION_NAME }}/workspaces" \
             -H "Authorization: Bearer $TF_API_TOKEN" \
             -H "Accept: application/json" \
             -H "Content-Type: application/vnd.api+json" \
@@ -96,16 +97,22 @@ jobs:
                   }
                 }
               }
-            }'
+            }')
 
-  Workspace_Access:
-    if: ${{ github.event.inputs.use_terraform_hcp == 'false' || github.event.inputs.use_terraform_hcp == '' }}
-    runs-on: ubuntu-latest
-    needs: create_workspace
-    steps:
+          echo "HTTP Response: $RESPONSE"
+
+          if [[ "$RESPONSE" -eq 201 ]]; then
+            echo "workspace_created=true" >> $GITHUB_ENV
+          else
+            echo "workspace_created=false" >> $GITHUB_ENV
+            echo "Failed to create workspace. Response: $(cat response.json)"
+            exit 1
+          fi
+
       - name: Echo Workspace Access URL
+        if: ${{ env.workspace_created == 'true' }}
         env:
-          WORKSPACE_NAME: ${{ needs.create_workspace.outputs.sanitized_repo_name }}
+          WORKSPACE_NAME: ${{ needs.get_repo_name.outputs.sanitized_repo_name }}
           ORGANIZATION_NAME: veloso
         run: |
           echo "The workspace for your repository has been successfully created."
@@ -115,6 +122,26 @@ jobs:
           echo "https://app.terraform.io/app/${{ env.ORGANIZATION_NAME }}/workspaces/${{ env.WORKSPACE_NAME }}"
           echo ""
           echo "Please proceed with the necessary actions to validate your changes and trigger the execution."
+
+
+  # Workspace_Access:
+  #   if: ${{ github.event.inputs.use_terraform_hcp == 'false' || github.event.inputs.use_terraform_hcp == '' || env.workspace_created == 'true' }}
+  #   runs-on: ubuntu-latest
+  #   needs: create_workspace
+  #   steps:
+  #     - name: Echo Workspace Access URL
+  #       env:
+  #         WORKSPACE_NAME: ${{ needs.create_workspace.outputs.sanitized_repo_name }}
+  #         ORGANIZATION_NAME: veloso
+  #       run: |
+  #         echo "The workspace for your repository has been successfully created."
+  #         echo "You can now access the workspace VCS and initiate the plan to test your infrastructure code."
+  #         echo ""
+  #         echo "Workspace Access URL:"
+  #         echo "https://app.terraform.io/app/${{ env.ORGANIZATION_NAME }}/workspaces/${{ env.WORKSPACE_NAME }}"
+  #         echo ""
+  #         echo "Please proceed with the necessary actions to validate your changes and trigger the execution."
+
 
   terraform_hcp:
     if: ${{ github.event.inputs.use_terraform_hcp == 'true' }}
